language: php

sudo: false

php:
    - 7.2
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit
